CREATE PROCEDURE AGREGAR_CLIENTE
    @CLIENTE_ID UNIQUEIDENTIFIER ,
    @TIPO_CLIENTE NVARCHAR(50),
    @NOMBRE NVARCHAR(150),
    @IDENTIFICACION NVARCHAR(50),
    @CORREO NVARCHAR(100) ,
    @TELEFONO NVARCHAR(20),
    @DIRECCION NVARCHAR(255) ,
    @FECHA_CREACION DATE ,
    @FECHA_ACTUALIZACION DATE ,
    @ESTADO_ID INT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO CLIENTES
    (
        CLIENTE_ID,
        TIPO_CLIENTE,
        NOMBRE,
        IDENTIFICACION,
        CORREO,
        TELEFONO,
        DIRECCION,
        FECHA_CREACION,
        FECHA_ACTUALIZACION,
        ESTADO_ID
    )
    VALUES
    (
        @CLIENTE_ID,
        @TIPO_CLIENTE,
        @NOMBRE,
        @IDENTIFICACION,
        @CORREO,
        @TELEFONO,
        @DIRECCION,
        @FECHA_CREACION,
        @FECHA_ACTUALIZACION,
        @ESTADO_ID
    );

    SELECT @CLIENTE_ID; 
END;
GO