CREATE PROCEDURE EDITAR_CLIENTE
    @CLIENTES_ID UNIQUEIDENTIFIER,
    @TIPO_CLIENTE NVARCHAR(50),
    @NOMBRE NVARCHAR(150),
    @IDENTIFICACION NVARCHAR(50),
    @CORREO NVARCHAR(100),
    @TELEFONO NVARCHAR(20),
    @DIRECCION NVARCHAR(255),
    @ESTADO_ID INT
AS
BEGIN
    SET NOCOUNT ON;

   
        UPDATE [dbo].[CLIENTES]
        SET 
            TIPO_CLIENTE = @TIPO_CLIENTE,
            NOMBRE = @NOMBRE,
            IDENTIFICACION = @IDENTIFICACION,
            CORREO = @CORREO,
            TELEFONO = @TELEFONO,
            DIRECCION = @DIRECCION,
            FECHA_ACTUALIZACION = GETDATE(),
            ESTADO_ID = @ESTADO_ID
        WHERE CLIENTES_ID = @CLIENTES_ID;
   
END;
GO
