CREATE PROCEDURE EDITAR_CLIENTE
    @CLIENTE_ID UNIQUEIDENTIFIER,
    @TIPO_CLIENTE NVARCHAR(50),
    @NOMBRE NVARCHAR(150),
    @IDENTIFICACION NVARCHAR(50),
    @CORREO NVARCHAR(100),
    @TELEFONO NVARCHAR(20),
    @DIRECCION NVARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE CLIENTES
    SET 
        TIPO_CLIENTE = @TIPO_CLIENTE,
        NOMBRE = @NOMBRE,
        IDENTIFICACION = @IDENTIFICACION,
        CORREO = @CORREO,
        TELEFONO = @TELEFONO,
        DIRECCION = @DIRECCION,
        FECHA_ACTUALIZACION = GETDATE()
    WHERE CLIENTE_ID = @CLIENTE_ID;

    SELECT @CLIENTE_ID AS CLIENTE_ID;
END
GO
