CREATE PROCEDURE ELIMINAR_CARRITOPRODUCTO
    @CarritoProductoId UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRANSACTION;

    DELETE FROM [dbo].[CARRITO_PRODUCTO]
    OUTPUT DELETED.CARRITO_ID
    WHERE CARRITO_PRODUCTO_ID = @CarritoProductoId;

    COMMIT TRANSACTION;
END;