CREATE PROCEDURE ELIMINAR_CARRITO
    @CarritoId UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  BEGIN TRANSACTION;

DELETE FROM [dbo].[CARRITO]
  WHERE CARRITO_ID = @CarritoId;

  COMMIT TRANSACTION;

  SELECT @CarritoId AS Eliminado;
END;