CREATE PROCEDURE ESTADO_EMPLEADO
  @IdEmpleado  UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  BEGIN TRANSACTION;
  UPDATE [dbo].[EMPLEADOS]
  SET ESTADO_ID = CASE 
                 WHEN ESTADO_ID = 1 THEN 2
                 WHEN ESTADO_ID = 2 THEN 1
                 ELSE ESTADO_ID 
               END
  WHERE IdEmpleado = @IdEmpleado;

  COMMIT TRANSACTION;

  SELECT @IdEmpleado;
END;