CREATE PROCEDURE ESTADO_CLIENTE
  @CLIENTE_ID UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  BEGIN TRANSACTION;

  UPDATE CLIENTES
  SET ESTADO_ID = CASE 
                     WHEN ESTADO_ID = 1 THEN 2
                     WHEN ESTADO_ID = 2 THEN 1
                     ELSE ESTADO_ID 
                   END
  WHERE CLIENTE_ID = @CLIENTE_ID;  

  COMMIT TRANSACTION;

  SELECT @CLIENTE_ID AS CLIENTE_ID;
END
GO
