CREATE PROCEDURE LIMPIEZA_CARRITOS
    @minutosExpiracion INT
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRANSACTION;
      UPDATE P
    SET P.STOCK = P.STOCK + CP.CANTIDAD
    FROM PRODUCTOS P
    INNER JOIN CARRITO_PRODUCTO CP ON P.PRODUCTOS_ID = CP.PRODUCTOS_ID
    INNER JOIN CARRITO C ON CP.CARRITO_ID = C.CARRITO_ID
    WHERE DATEADD(MINUTE, @MinutosExpiracion, C.FECHA_CREACION) <= GETUTCDATE();

    DELETE CP
    FROM CARRITO_PRODUCTO CP
    INNER JOIN CARRITO C ON CP.CARRITO_ID = C.CARRITO_ID
    WHERE DATEADD(MINUTE, @MinutosExpiracion, C.FECHA_CREACION) <= GETUTCDATE();

    DELETE FROM CARRITO
    WHERE DATEADD(MINUTE, @MinutosExpiracion, FECHA_CREACION) <= GETUTCDATE();

    COMMIT TRANSACTION;
END;