CREATE PROCEDURE OBTENER_CARRITOS_POR_USUARIO
    @UsuarioId UNIQUEIDENTIFIER
AS
BEGIN
    SELECT CARRITO_ID as carritoId, FECHA_CREACION as fechaCreacion, Total
    FROM Carrito
    WHERE USUARIO_ID = @UsuarioId
END