CREATE PROCEDURE [dbo].[OBTENER_CATEGORIAS_HIJAS]
	 @IdPadre UNIQUEIDENTIFIER
AS
BEGIN
   SELECT 
    C.CATEGORIAS_ID AS CategoriasId,
    C.NOMBRE AS Nombre,
    C.PADRE_ID AS PadreId,
    C.DESCRIPCION AS Descripcion,
    C.FECHA_CREACION AS FechaCreacion,
    E.TIPO AS Estado
  FROM CATEGORIAS C
  INNER JOIN ESTADOS E ON C.ESTADO_ID = E.ESTADO_ID
     WHERE C.PADRE_ID = @IdPadre AND C.CATEGORIAS_ID <> @IdPadre
END