CREATE PROCEDURE VER_CLIENTE_POR_ID
    @CLIENTE_ID UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        CLIENTE_ID,
        TIPO_CLIENTE,
        NOMBRE,
        IDENTIFICACION,
       CORREO,
        TELEFONO,
        DIRECCION,
        FECHA_CREACION,
        FECHA_ACTUALIZACION,
        ESTADO_ID  
    FROM CLIENTES  
    WHERE CLIENTE_ID = @CLIENTE_ID;
END;
GO