CREATE PROCEDURE [dbo].[VER_CLIENTE_POR_ID]
    @CLIENTES_ID UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        CLIENTES_ID,
        TIPO_CLIENTE,
        NOMBRE,
        IDENTIFICACION,
       CORREO,
        TELEFONO,
        DIRECCION,
        FECHA_CREACION,
        FECHA_ACTUALIZACION,
        ESTADO_ID  
    FROM CLIENTES  
    WHERE CLIENTES_ID = @CLIENTES_ID;
END;
GO
