CREATE PROCEDURE VER_CLIENTES
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        CLIENTE_ID,
        TIPO_CLIENTE,
        NOMBRE,
        IDENTIFICACION,
        CORREO,
        TELEFONO,
        DIRECCION,
        FECHA_CREACION,
        FECHA_ACTUALIZACION,
        ESTADO_ID   
    FROM CLIENTES;
END;
GO
