CREATE PROCEDURE VER_CATEGORIAS
AS
BEGIN
  SET NOCOUNT ON;

  SELECT 
    C.CATEGORIAS_ID AS CategoriasId,
    C.NOMBRE AS Nombre,
    C.PADRE_ID AS PadreId,
    CP.NOMBRE AS NombrePadre,
    C.DESCRIPCION AS Descripcion,
    C.FECHA_CREACION AS FechaCreacion,
    E.TIPO AS Estado
  FROM CATEGORIAS C
  LEFT JOIN CATEGORIAS CP ON C.PADRE_ID = CP.CATEGORIAS_ID
  INNER JOIN ESTADOS E ON C.ESTADO_ID = E.ESTADO_ID;
END;