CREATE PROCEDURE DESCONTAR_STOCK
    @ProductoId UNIQUEIDENTIFIER,
    @Cantidad INT
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE PRODUCTOS
    SET STOCK = STOCK - @Cantidad
    WHERE PRODUCTOS_ID = @ProductoId;
END
