CREATE PROCEDURE EDITAR_CATEGORIA
 @IdCategoria UNIQUEIDENTIFIER,
  @Nombre NVARCHAR(255),
  @Descripcion NVARCHAR(255),
  @Icono NVARCHAR(255) 
AS
BEGIN
  SET NOCOUNT ON;

  BEGIN TRANSACTION;

 UPDATE dbo.CATEGORIAS
  SET
    NOMBRE = @Nombre,
    DESCRIPCION = @Descripcion,
    ICONO = @Icono
  WHERE CATEGORIAS_ID = @IdCategoria;

  COMMIT TRANSACTION;

  SELECT @IdCategoria AS Resultado;
END;
