CREATE PROCEDURE OBTENER_PRODUCTOS_X_CATEGORIA
   @CategoriaId uniqueidentifier
AS
BEGIN
  SET NOCOUNT ON;

  SELECT 
    P.PRODUCTOS_ID AS IdProducto,
    P.NOMBRE AS Nombre,
    P.MARCA AS Marca,
    P.PRECIO AS Precio,
    P.DESCRIPCION AS Descripcion,
    P.STOCK AS Stock,
    P.IMAGEN_URL AS ImagenUrl,
    P.FECHA_CREACION AS FechaCreacion,
    PR.Nombre_PROVEEDOR AS NombreProveedor,
    C.NOMBRE AS Categoria,
    E.TIPO AS Estado
  FROM PRODUCTOS P
  INNER JOIN PROVEEDORES PR ON P.PROVEEDOR_ID = PR.PROVEEDOR_ID
  INNER JOIN CATEGORIAS C ON P.CATEGORIAS_ID = C.CATEGORIAS_ID
  INNER JOIN ESTADOS E ON P.ESTADO_ID = E.ESTADO_ID
  WHERE P.CATEGORIAS_ID = @CategoriaId;
END;
