CREATE PROCEDURE VER_PRODUCTO_POR_ID
  @IdProducto UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  SELECT 
    P.PRODUCTOS_ID AS IdProducto,
    P.NOMBRE AS Nombre,
    P.MARCA AS Marca,
    P.PRECIO AS Precio,
    P.DESCRIPCION AS Descripcion,
    P.STOCK AS Stock,
    P.IMAGEN_URL AS ImagenUrl,
    P.FECHA_CREACION AS FechaCreacion,
    pr.Nombre_PROVEEDOR AS NombreProveedor,
    C.NOMBRE AS Categoria,
    E.TIPO AS Estado,
    P.PROVEEDOR_ID AS IdProveedor,
    P.CATEGORIAS_ID AS IdCategoria

  FROM PRODUCTOS P
  INNER JOIN Proveedores PR ON P.PROVEEDOR_ID = PR.PROVEEDOR_ID
  INNER JOIN CATEGORIAS C ON P.CATEGORIAS_ID = C.CATEGORIAS_ID
  INNER JOIN ESTADOS E ON P.ESTADO_ID = E.ESTADO_ID
  WHERE P.PRODUCTOS_ID = @IdProducto;
END;