CREATE PROCEDURE VER_CATEGORIA_POR_ID
  @IdCategoria UNIQUEIDENTIFIER
AS
BEGIN
  SET NOCOUNT ON;

  SELECT 
    C.CATEGORIAS_ID AS CategoriasId,
    C.NOMBRE AS Nombre,
    C.ICONO AS Icono,
    C.PADRE_ID AS PadreId,
    C.DESCRIPCION AS Descripcion,
    C.FECHA_CREACION AS FechaCreacion,
    E.TIPO AS Estado
  FROM CATEGORIAS C
  INNER JOIN ESTADOS E ON C.ESTADO_ID = E.ESTADO_ID
  WHERE C.CATEGORIAS_ID = @IdCategoria;
END;
