CREATE TABLE [dbo].[CLIENTES]
(
    [CLIENTE_ID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [TIPO_CLIENTE] NVARCHAR(50) NOT NULL,
    [NOMBRE] NVARCHAR(150) NOT NULL,
    [IDENTIFICACION] NVARCHAR(50) UNIQUE NOT NULL,
    [CORREO] NVARCHAR(100) UNIQUE NOT NULL,
    [TELEFONO] NVARCHAR(20) NOT NULL,
    [DIRECCION] NVARCHAR(255) NOT NULL,
    [FECHA_CREACION] DATE NOT NULL,
    [FECHA_ACTUALIZACION] DATE NULL ,
    [ESTADO_ID] INT NOT NULL,

    CONSTRAINT [FK_CLIENTES_ESTADOS] FOREIGN KEY ([ESTADO_ID]) 
        REFERENCES [dbo].[ESTADOS]([ESTADO_ID])
      
);
