CREATE TABLE EMPLEADOS (
    IdEmpleado UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    
    Cedula NVARCHAR(9) NOT NULL UNIQUE,
    NombreCompleto NVARCHAR(150) NOT NULL,
    Telefono NVARCHAR(8) NOT NULL,
    CorreoElectronico NVARCHAR(150) NOT NULL,
    Puesto NVARCHAR(100) NOT NULL,
    Padecimientos NVARCHAR(250) NOT NULL,
    CuentaBancaria NVARCHAR(20) NOT NULL,
    TipoContrato NVARCHAR(50) NOT NULL,
    Jornada NVARCHAR(50) NOT NULL,
     FechaRegistro DATE NOT NULL,
    FechaIngreso DATE NOT NULL,
     ESTADO_ID INT NOT NULL,
    FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS(ESTADO_ID)
);