CREATE TABLE [dbo].[PRODUCTOS]
(
  [PRODUCTOS_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  NOMBRE NVARCHAR(255) not null,
  MARCA NVARCHAR(255) not null,
  PRECIO DECIMAL(8,2) NOT NULL,
  DESCRIPCION NVARCHAR(255),
  PROVEEDOR_ID UNIQUEIDENTIFIER NOT NULL,
  CATEGORIAS_ID UNIQUEIDENTIFIER NOT NULL,
  STOCK INT NOT NULL,
  IMAGEN_URL NVARCHAR(255),
  FECHA_CREACION DATE NOT NULL,
  ESTADO_ID INT NOT NULL,
  FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDORES(PROVEEDOR_ID),
  FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS(ESTADO_ID),
  FOREIGN KEY (CATEGORIAS_ID) REFERENCES CATEGORIAS(CATEGORIAS_ID)
  )