CREATE PROCEDURE CONTAR_HIJAS_ACTIVAS
    @IdCategoria UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS CantidadHijas
    FROM dbo.CATEGORIAS
    WHERE PADRE_ID = @IdCategoria
      AND ESTADO_ID = 1
      AND PADRE_ID IS NOT NULL;
END