CREATE PROCEDURE EDITAR_CARRITO
    @IdCarrito UNIQUEIDENTIFIER,
    @Total DECIMAL(18, 2)
AS
BEGIN
  SET NOCOUNT ON;
    BEGIN TRANSACTION;

    UPDATE Carrito
    SET Total = @Total
    WHERE CARRITO_ID = @IdCarrito
    COMMIT TRANSACTION;
    SELECT @IdCarrito
END