CREATE PROCEDURE ELIMINAR_TOTAL
    @CarritoId UNIQUEIDENTIFIER
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRANSACTION;
    DELETE FROM CARRITO_PRODUCTO WHERE CARRITO_ID = @CarritoId;
    DELETE FROM CARRITO WHERE CARRITO_ID = @CarritoId;

    COMMIT TRANSACTION;
END;