    CREATE TABLE [dbo].[CARRITO]
(
  [CARRITO_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  USUARIO_ID UNIQUEIDENTIFIER not null,
  FECHA_CREACION DATETIME NOT NULL,
  TOTAL DECIMAL(18,2) NOT NULL,
  FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID)
  )