CREATE TABLE [dbo].[CATEGORIAS] (
    [CATEGORIAS_ID]  UNIQUEIDENTIFIER NOT NULL,
    [PADRE_ID]       UNIQUEIDENTIFIER NULL,
    [NOMBRE]         NVARCHAR (255)   NOT NULL,
    [FECHA_CREACION] DATE             NOT NULL,
    [DESCRIPCION]    NVARCHAR (255)   NULL,
    [ICONO]          NVARCHAR(255)   NULL,
    [ESTADO_ID]      INT              NOT NULL,
    CONSTRAINT [PKtmp_ms_xC984683C53574C6D] PRIMARY KEY CLUSTERED ([CATEGORIAS_ID] ASC),
    FOREIGN KEY ([ESTADO_ID]) REFERENCES [dbo].[ESTADOS] ([ESTADO_ID]),
    FOREIGN KEY ([PADRE_ID]) REFERENCES [dbo].[CATEGORIAS] ([CATEGORIAS_ID])
);