CREATE TABLE [dbo].[CATEGORIAS] (
    [CATEGORIAS_ID]  UNIQUEIDENTIFIER NOT NULL,
    [PADRE_ID]       UNIQUEIDENTIFIER NULL,
    [NOMBRE]         NVARCHAR(255)   NOT NULL,
    [FECHA_CREACION] DATE             NOT NULL,
    [DESCRIPCION]    NVARCHAR(255)   NULL,
    [ESTADO_ID]      INT              NOT NULL,
    [ICONO]          NVARCHAR(255)   NULL,
    CONSTRAINT [PK_CATEGORIAS] PRIMARY KEY CLUSTERED ([CATEGORIAS_ID] ASC),
    CONSTRAINT [FK_CATEGORIAS_ESTADOS] FOREIGN KEY ([ESTADO_ID]) REFERENCES [dbo].[ESTADOS] ([ESTADO_ID]),
    CONSTRAINT [FK_CATEGORIAS_PADRE] FOREIGN KEY ([PADRE_ID]) REFERENCES [dbo].[CATEGORIAS] ([CATEGORIAS_ID])
);