CREATE TABLE Proveedores (
    PROVEEDOR_ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    Nombre_PROVEEDOR NVARCHAR(100) NOT NULL,
    Correo_ELECTRONICO NVARCHAR(100) NOT NULL,
    Telefono NVARCHAR(20) NOT NULL,
    Direccion NVARCHAR(200) NULL,
    Nombre_Contacto NVARCHAR(100) NOT NULL,
    Fecha_Registro DATETIME NOT NULL,
	TIPO NVARCHAR(MAX) NOT NULL,
     ESTADO_ID INT NOT NULL,
    FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS(ESTADO_ID)
);